- name: install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: application setup   
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app   

- name: start application
  ansible.builtin.import_role:
    name: common
    task_from: systemd-setup           